Repository materialsproject/pymatgen, pull requests merged in 2023-09, with the labels that each got.

#3288 MatPESStaticSet restore GGA tag removal if xc_functional.upper() == "R2SCAN"
  pymatgen/io/vasp/sets.py
  tests/io/vasp/test_sets.py
Labels: io, fix, vasp

#3228 xyz.__iter__() -> iter(xyz)
  pymatgen/analysis/chemenv/connectivity/environment_nodes.py
  pymatgen/analysis/graphs.py
  pymatgen/apps/battery/battery_abc.py
  pymatgen/core/composition.py
  pymatgen/core/structure.py
  pymatgen/core/tensors.py
  pymatgen/core/units.py
  pymatgen/electronic_structure/core.py
  pymatgen/entries/entry_tools.py
  pymatgen/io/abinit/abitimer.py
  pymatgen/io/abinit/inputs.py
  pymatgen/io/abinit/pseudos.py
  pymatgen/io/cp2k/inputs.py
  pymatgen/io/nwchem.py
  pymatgen/io/xyz.py
  pymatgen/util/testing.py
  tests/core/test_units.py
  tests/io/abinit/test_pseudos.py
  tests/phonon/test_bandstructure.py
Labels: DX

#3295 Deprecate overlooked `from/as_..._string` methods
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  dev_scripts/update_pt_data.py
  pymatgen/alchemy/materials.py
  pymatgen/alchemy/transmuters.py
  pymatgen/cli/pmg_structure.py
  pymatgen/core/operations.py
  pymatgen/core/periodic_table.py
  pymatgen/io/cssr.py
  pymatgen/io/feff/inputs.py
  pymatgen/io/fiesta.py
  pymatgen/io/gaussian.py
  pymatgen/io/nwchem.py
  pymatgen/io/packmol.py
  pymatgen/io/vasp/inputs.py
  pymatgen/io/vasp/outputs.py
  pymatgen/io/zeopp.py
  pymatgen/symmetry/settings.py
  tasks.py
  tests/core/test_operations.py
  tests/io/test_gaussian.py
Labels: deprecation

#3308 Fix IndexError when parsing Hessian from Gaussian frequency job
  pymatgen/io/gaussian.py
  tests/files/.pytest-split-durations
  tests/io/test_gaussian.py
Labels: io, fix

#3309 v2023.9.10
  .github/release.yml
  CHANGES.md
  docs/CHANGES.md
  pymatgen/analysis/magnetism/heisenberg.py
  pymatgen/vis/structure_chemview.py
  setup.py
Labels: release

#3310 Fix `MPSOCSet` raising ValueError on `structure=None`
  pymatgen/io/vasp/sets.py
Labels: io, fix, vasp

#3311 Update @arosen93 to @Andrew-S-Rosen
  CHANGES.md
  docs/CHANGES.md
  docs/assets/metadata.yml
  docs/team.md
  pymatgen/io/ase.py
Labels: housekeeping, docs

#3312 Fix ruff PERF401
  pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py
  pymatgen/analysis/molecule_structure_comparator.py
  pymatgen/analysis/piezo_sensitivity.py
  pymatgen/analysis/pourbaix_diagram.py
  pymatgen/io/vasp/inputs.py
  tests/analysis/chemenv/coordination_environments/test_voronoi.py
  tests/analysis/test_piezo_sensitivity.py
  tests/analysis/test_pourbaix_diagram.py
  tests/analysis/test_reaction_calculator.py
  tests/analysis/test_structure_matcher.py
  tests/ext/test_matproj.py
Labels: housekeeping

#3313 Remove redundant my_? prefix from variables
  dev_scripts/chemenv/check_new_coordination_geometry.py
  dev_scripts/chemenv/get_plane_permutations_optimized.py
  dev_scripts/chemenv/test_algos.py
  dev_scripts/chemenv/view_environment.py
  pymatgen/analysis/chemenv/connectivity/connected_components.py
  pymatgen/analysis/chemenv/coordination_environments/chemenv_strategies.py
  pymatgen/analysis/chemenv/coordination_environments/coordination_geometries.py
  pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py
  pymatgen/analysis/chemenv/coordination_environments/structure_environments.py
  pymatgen/analysis/chemenv/coordination_environments/voronoi.py
  pymatgen/analysis/chemenv/utils/graph_utils.py
  pymatgen/analysis/chemenv/utils/scripts_utils.py
  pymatgen/analysis/local_env.py
  pymatgen/analysis/phase_diagram.py
  pymatgen/core/operations.py
  pymatgen/ext/cod.py
  pymatgen/io/qchem/sets.py
  pymatgen/io/vasp/sets.py
  pymatgen/io/wannier90.py
  pymatgen/vis/structure_vtk.py
  tests/analysis/chemenv/connectivity/test_connected_components.py
  tests/analysis/chemenv/coordination_environments/test_coordination_geometry_finder.py
  tests/analysis/chemenv/coordination_environments/test_structure_environments.py
  tests/analysis/chemenv/coordination_environments/test_weights.py
  tests/analysis/test_pourbaix_diagram.py
  tests/io/qchem/test_inputs.py
  tests/io/vasp/test_outputs.py
Labels: housekeeping

#3314 Allow usage of `calculate_ng` with a custom ENCUT and PREC values for VASP input sets
  pymatgen/io/vasp/sets.py
  tests/io/vasp/test_sets.py
Labels: enhancement, io, vasp

#3315 Fix internal `SymmOp.from_xyz_string` and `MagSymmOp.from_xyzt_string` deprecation warnings
  pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py
  pymatgen/analysis/chemenv/coordination_environments/structure_environments.py
  pymatgen/core/operations.py
  pymatgen/io/cif.py
Labels: housekeeping

#3318 Fix copy-paste error making `MagSymmOp.as_xyzt_string` class method
  pymatgen/analysis/chemenv/coordination_environments/chemenv_strategies.py
  pymatgen/analysis/chemenv/utils/coordination_geometry_utils.py
  pymatgen/analysis/chemenv/utils/func_utils.py
  pymatgen/analysis/chemenv/utils/graph_utils.py
  pymatgen/analysis/magnetism/heisenberg.py
  pymatgen/analysis/pourbaix_diagram.py
  pymatgen/core/operations.py
  tests/core/test_operations.py
Labels: fix, core

#3320 Google-style doc strings for class attributes
  pymatgen/analysis/pourbaix_diagram.py
  pymatgen/analysis/surface_analysis.py
  pymatgen/analysis/wulff.py
  pymatgen/command_line/enumlib_caller.py
  pymatgen/core/operations.py
  pymatgen/core/periodic_table.py
  pymatgen/core/surface.py
  pymatgen/core/tensors.py
  pymatgen/electronic_structure/bandstructure.py
  pymatgen/electronic_structure/cohp.py
  pymatgen/electronic_structure/dos.py
  pymatgen/io/common.py
  pymatgen/io/exciting/inputs.py
  pymatgen/io/gaussian.py
  pymatgen/io/lobster/outputs.py
  pymatgen/io/vasp/inputs.py
  pymatgen/io/vasp/outputs.py
  pymatgen/io/wannier90.py
  pymatgen/phonon/dos.py
  pymatgen/symmetry/analyzer.py
  pymatgen/symmetry/groups.py
  pymatgen/util/provenance.py
Labels: docs

#3325 Readme notice regarding updated pymatgen publication
  README.md
  docs/index.md
Labels: docs

#3327 Fix `AttributeError` in `BSPlotter.get_plot()`
  pymatgen/electronic_structure/plotter.py
  pymatgen/phonon/plotter.py
Labels: fix, data viz, electronic structure

#3330 Use `ax = fig.add_subplot(projection='3d')` to create `Axes3D`
  pymatgen/analysis/wulff.py
  pymatgen/util/plotting.py
  tests/analysis/test_wulff.py
Labels: fix, data viz, electronic structure

#3331 Fix `ruff` A001 violations: Variable is shadowing a Python builtin
  .pre-commit-config.yaml
  pymatgen/alchemy/filters.py
  pymatgen/analysis/diffraction/tem.py
  pymatgen/analysis/diffraction/xrd.py
  pymatgen/analysis/elasticity/elastic.py
  pymatgen/analysis/structure_matcher.py
  pymatgen/analysis/wulff.py
  pymatgen/core/ion.py
  pymatgen/core/lattice.py
  pymatgen/io/cif.py
  pymatgen/io/feff/inputs.py
  pymatgen/io/lobster/inputs.py
  pymatgen/io/vasp/help.py
  pymatgen/io/vasp/sets.py
  tests/analysis/diffraction/test_tem.py
  tests/analysis/elasticity/test_elastic.py
  tests/analysis/test_reaction_calculator.py
  tests/command_line/test_gulp_caller.py
  tests/core/test_lattice.py
  tests/core/test_surface.py
  tests/io/cp2k/test_inputs.py
  tests/io/vasp/test_sets.py
  tests/util/test_num.py
Labels: housekeeping

#3333 Delete unused or numpy-provided routines from `pymatgen.util.num`
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  pymatgen/analysis/structure_analyzer.py
  pymatgen/core/lattice.py
  pymatgen/io/abinit/abitimer.py
  pymatgen/util/num.py
  tests/util/test_num.py
Labels: housekeeping, breaking

#3335 fix ruff FBT003: Boolean positional value in function call
  pymatgen/analysis/chemenv/coordination_environments/coordination_geometries.py
  pymatgen/analysis/elasticity/elastic.py
  pymatgen/analysis/eos.py
  pymatgen/analysis/molecule_matcher.py
  pymatgen/analysis/reaction_calculator.py
  pymatgen/analysis/structure_analyzer.py
  pymatgen/analysis/structure_matcher.py
  pymatgen/core/composition.py
  pymatgen/core/ion.py
  pymatgen/core/structure.py
  pymatgen/electronic_structure/boltztrap.py
  pymatgen/electronic_structure/boltztrap2.py
  pymatgen/electronic_structure/plotter.py
  pymatgen/io/abinit/abitimer.py
  pymatgen/io/abinit/netcdf.py
  pymatgen/io/abinit/pseudos.py
  pymatgen/io/cp2k/inputs.py
  pymatgen/io/cp2k/sets.py
  pymatgen/io/feff/inputs.py
  pymatgen/io/gaussian.py
  pymatgen/io/lammps/data.py
  pymatgen/io/vasp/inputs.py
  pymatgen/symmetry/analyzer.py
  pymatgen/util/provenance.py
  pymatgen/util/string.py
  pymatgen/vis/structure_vtk.py
  pyproject.toml
  tests/analysis/chemenv/coordination_environments/test_voronoi.py
  tests/analysis/test_local_env.py
  tests/analysis/test_structure_matcher.py
  tests/apps/battery/test_conversion_battery.py
  tests/apps/battery/test_insertion_battery.py
  tests/apps/borg/test_hive.py
  tests/command_line/test_gulp_caller.py
  tests/core/test_composition.py
  tests/core/test_lattice.py
  tests/core/test_operations.py
  tests/core/test_structure.py
  tests/core/test_tensors.py
  tests/files/.pytest-split-durations
  tests/io/abinit/test_abiobjects.py
  tests/io/cp2k/test_inputs.py
  tests/io/lammps/test_data.py
  tests/io/test_cif.py
  tests/io/test_phonopy.py
  tests/io/vasp/test_inputs.py
  tests/optimization/test_linear_assignment.py
  tests/symmetry/test_analyzer.py
  tests/transformations/test_advanced_transformations.py
  tests/transformations/test_standard_transformations.py
Labels: housekeeping

#3337 Fix breaking change to `CoherentInterfaceBuilder.get_interfaces`
  pymatgen/analysis/interfaces/coherent_interfaces.py
  tests/analysis/interfaces/test_coherent_interface.py
Labels: fix, analysis

#3339 Snake case test method names
  pymatgen/apps/borg/hive.py
  pymatgen/core/interface.py
  pymatgen/core/operations.py
  pymatgen/core/periodic_table.py
  pymatgen/ext/matproj.py
  pymatgen/io/abinit/abiobjects.py
  pymatgen/io/feff/sets.py
  pymatgen/io/gaussian.py
  pymatgen/symmetry/analyzer.py
  pymatgen/transformations/advanced_transformations.py
  tests/analysis/chemenv/utils/test_func_utils.py
  tests/analysis/test_piezo_sensitivity.py
  tests/apps/battery/test_plotter.py
  tests/core/test_sites.py
  tests/entries/test_compatibility.py
  tests/files/.pytest-split-durations
  tests/io/feff/test_sets.py
  tests/io/lobster/test_inputs.py
  tests/io/qchem/test_inputs.py
  tests/io/qchem/test_outputs.py
  tests/io/qchem/test_utils.py
  tests/io/test_cif.py
  tests/io/test_shengbte.py
  tests/io/test_wannier90.py
  tests/io/vasp/test_outputs.py
  tests/io/vasp/test_sets.py
  tests/phonon/test_thermal_displacements.py
Labels: housekeeping

#3332 Always return 0 for `Composition.oxi_state_guesses()` of diatomic molecules
  pymatgen/core/composition.py
  pymatgen/core/periodic_table.py
  pymatgen/entries/compatibility.py
  tests/core/test_composition.py
  tests/entries/test_compatibility.py
  tests/files/.pytest-split-durations
Labels: fix, core

#3344 Fix: `TestMITMPRelaxSet.test_nelect` claimed to but wasn't testing disordered structure
  pymatgen/core/composition.py
  pymatgen/io/vasp/inputs.py
  pymatgen/io/vasp/sets.py
  pymatgen/transformations/advanced_transformations.py
  tests/io/qchem/test_sets.py
  tests/io/vasp/test_outputs.py
  tests/io/vasp/test_sets.py
Labels: io, fix, vasp

#3347 Fix `TestPotcar.test_write` polluting git repo on failure
  pymatgen/core/structure.py
  pymatgen/io/vasp/inputs.py
  tests/core/test_structure.py
  tests/io/vasp/test_inputs.py
Labels: tests, DX

#3352 Bump min `numpy` to v1.25.0
  setup.py
Labels: outdated, pkg

#3353 Revert `openbabel.OBAlign()` in `molecule_matcher.py` to use positional args for `includeH`, `symmetry`
  pymatgen/analysis/molecule_matcher.py
Labels: fix, molecules

#3357 Chargemol minor refactor
  pymatgen/command_line/chargemol_caller.py
  tests/command_line/test_chargemol_caller.py
Labels: housekeeping, cli

#3360 Breaking typo fix: `Targe(tt->t)edPenaltiedAbundanceChemenvStrategy`
  pymatgen/analysis/chemenv/coordination_environments/chemenv_strategies.py
  pymatgen/analysis/chemenv/utils/scripts_utils.py
  tasks.py
  tests/analysis/test_ewald.py
  tests/analysis/test_molecule_matcher.py
  tests/analysis/test_pourbaix_diagram.py
Labels: housekeeping, breaking

#3351 Breaking: New method of POTCAR validation
  pymatgen/io/vasp/inputs.py
  pymatgen/io/vasp/outputs.py
  pymatgen/io/vasp/potcar_summary_stats.json.gz
  tests/io/lobster/test_inputs.py
  tests/io/vasp/test_inputs.py
  tests/io/vasp/test_sets.py
Labels: io, vasp, breaking, api, UX

#3362 Fix `TestMPResterNewBasic` + `AseAtomsAdaptor` test errors and `TransformedStructure.from_snl` overwriting `hist` variable
  pymatgen/alchemy/materials.py
  pymatgen/electronic_structure/boltztrap2.py
  pymatgen/entries/computed_entries.py
  pymatgen/ext/optimade.py
  pymatgen/io/ase.py
  pymatgen/io/vasp/outputs.py
  tests/alchemy/test_filters.py
  tests/command_line/test_gulp_caller.py
  tests/ext/test_matproj.py
  tests/files/.pytest-split-durations
  tests/io/test_ase.py
  tests/io/vasp/test_inputs.py
  tests/io/vasp/test_sets.py
Labels: tests, fix, ci

#3356 Add alias `.to_file()` for `.to()` method of structures and molecules
  pymatgen/core/structure.py
  tests/core/test_structure.py
Labels: needs testing, api

#3343 Fix `TypeError`: can only join an iterable with AECCAR in `VolumetricData.write_file`
  pymatgen/command_line/chargemol_caller.py
  pymatgen/io/vasp/outputs.py
  tests/io/vasp/test_outputs.py
Labels: io, fix, vasp
