Repository materialsproject/pymatgen, pull requests merged in 2023-04, with the labels that each got.

#2910 bug fix for potcar parsing
  pymatgen/io/vasp/inputs.py
  pymatgen/io/vasp/tests/test_inputs.py
Labels: io, bug fix

#2940 Fix CI errors
  .pre-commit-config.yaml
  dev_scripts/chemenv/get_plane_permutations_optimized.py
  dev_scripts/chemenv/plane_multiplicity.py
  pymatgen/analysis/graphs.py
  pymatgen/analysis/tests/test_graphs.py
  pymatgen/entries/mixing_scheme.py
  pymatgen/entries/tests/test_mixing_scheme.py
Labels: bug fix

#2941 Add ResParser support for reading files with spin values
  pymatgen/io/res.py
  pymatgen/io/tests/test_res.py
  test_files/res/spins-in-last-col.res
Labels: enhancement, io

#2948 Ignore bad unicode characters in Structure.from_file()
  pymatgen/core/structure.py
  pymatgen/core/tests/test_structure.py
  test_files/bad-unicode-gh-2947.mcif
Labels: io

#2950 Fixed Wulff shape for new versions of matplotlib
  pymatgen/analysis/wulff.py
Labels: fix

#2953 Test figure returned by WulffShape.get_plot() contains single Axes3D
  pymatgen/analysis/tests/test_wulff.py
  pymatgen/analysis/wulff.py
Labels: fix, data viz

#2954 Fix `Cp2kOutput.spin_polarized()` likely not doing what author intended
  pymatgen/io/cp2k/outputs.py
Labels: io, fix

#2945 For MPcules: Molecule Trajectory and graph hashes
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGES.rst
  docs_rst/change_log.rst
  pymatgen/alchemy/filters.py
  pymatgen/analysis/chemenv/coordination_environments/chemenv_strategies.py
  pymatgen/analysis/chemenv/utils/graph_utils.py
  pymatgen/analysis/diffraction/tests/test_xrd.py
  pymatgen/analysis/molecule_matcher.py
  pymatgen/analysis/structure_prediction/substitution_probability.py
  pymatgen/apps/battery/insertion_battery.py
  pymatgen/apps/borg/hive.py
  pymatgen/core/interface.py
  pymatgen/core/operations.py
  pymatgen/core/periodic_table.py
  pymatgen/core/structure.py
  pymatgen/core/surface.py
  pymatgen/core/tensors.py
  pymatgen/core/tests/test_trajectory.py
  pymatgen/core/trajectory.py
  pymatgen/entries/computed_entries.py
  pymatgen/io/qchem/outputs.py
  pymatgen/io/shengbte.py
  pymatgen/io/vasp/outputs.py
  pymatgen/io/vasp/sets.py
  pymatgen/symmetry/structure.py
  pymatgen/util/graph_hashing.py
  pymatgen/util/tests/test_graph_hashing.py
Labels: enhancement

#2955 `self.assertArrayEqual->assert`
  dev_scripts/chemenv/get_plane_permutations_optimized.py
  dev_scripts/update_pt_data.py
  pymatgen/analysis/adsorption.py
  pymatgen/analysis/bond_valence.py
  pymatgen/analysis/chemenv/connectivity/tests/test_environment_nodes.py
  pymatgen/analysis/chemenv/connectivity/tests/test_structure_connectivity.py
  pymatgen/analysis/chemenv/coordination_environments/tests/test_coordination_geometries.py
  pymatgen/analysis/chemenv/utils/tests/test_coordination_geometry_utils.py
  pymatgen/analysis/chemenv/utils/tests/test_graph_utils.py
  pymatgen/analysis/chempot_diagram.py
  pymatgen/analysis/cost.py
  pymatgen/analysis/diffraction/tests/test_tem.py
  pymatgen/analysis/dimensionality.py
  pymatgen/analysis/elasticity/strain.py
  pymatgen/analysis/ewald.py
  pymatgen/analysis/local_env.py
  pymatgen/analysis/path_finder.py
  pymatgen/analysis/pourbaix_diagram.py
  pymatgen/command_line/enumlib_caller.py
  pymatgen/core/tests/test_tensors.py
  pymatgen/core/trajectory.py
  pymatgen/io/res.py
  pymatgen/symmetry/maggroups.py
  pymatgen/util/graph_hashing.py
  pyproject.toml
Labels: housekeeping

#2937 fix GaussianOutput bug with multiple route lines
  pymatgen/io/gaussian.py
  pymatgen/io/tests/test_gaussian.py
  test_files/molecules/EC.log.gz
Labels: io, fix

#2951 Fix ValueError when passing `selective_dynamics` to `Poscar`
  pymatgen/core/tests/test_trajectory.py
  pymatgen/io/vasp/inputs.py
  pymatgen/io/vasp/tests/test_inputs.py
Labels: io
