Repository materialsproject/pymatgen, pull requests merged in 2023-05, with the labels that each got.

#2967 Link /addons from new subsection on /contributing page
  docs_rst/contributing.rst
Labels: docs

#2969 Change Yb pseudo-potential on all VASP input sets: Yb_(2->3)
  pymatgen/io/vasp/MPAbsorptionSet.yaml
  pymatgen/io/vasp/MPHSERelaxSet.yaml
  pymatgen/io/vasp/MPRelaxSet.yaml
  pymatgen/io/vasp/MPSCANRelaxSet.yaml
  pymatgen/io/vasp/MVLGWSet.yaml
  pymatgen/io/vasp/MVLRelax52Set.yaml
Labels: fix, vasp

#2973 fix recursion error by adding copy and deepcopy dunder methods
  pymatgen/analysis/chemenv/coordination_environments/tests/test_read_write.py
  pymatgen/io/core.py
  pymatgen/io/tests/test_core.py
Labels: fix

#2972 Revert to `Yb_2` on pre-`PBE_54` input sets
  pymatgen/analysis/interface_reactions.py
  pymatgen/analysis/tests/test_interface_reactions.py
  pymatgen/analysis/transition_state.py
  pymatgen/apps/borg/hive.py
  pymatgen/cli/pmg_config.py
  pymatgen/command_line/bader_caller.py
  pymatgen/command_line/chargemol_caller.py
  pymatgen/command_line/critic2_caller.py
  pymatgen/command_line/enumlib_caller.py
  pymatgen/core/tests/test_lattice.py
  pymatgen/core/tests/test_sites.py
  pymatgen/core/tests/test_trajectory.py
  pymatgen/io/ase.py
  pymatgen/io/cp2k/outputs.py
  pymatgen/io/lammps/inputs.py
  pymatgen/io/lammps/outputs.py
  pymatgen/io/tests/test_cif.py
  pymatgen/io/vasp/MPAbsorptionSet.yaml
  pymatgen/io/vasp/MPHSERelaxSet.yaml
  pymatgen/io/vasp/MPRelaxSet.yaml
  pymatgen/io/vasp/MVLRelax52Set.yaml
  pymatgen/io/vasp/inputs.py
  pymatgen/io/vasp/outputs.py
  pymatgen/io/vasp/sets.py
  pymatgen/io/vasp/tests/test_sets.py
  pyproject.toml
Labels: fix

#2977 Enable all ruff pylint rules (excl. PLR)
  .pre-commit-config.yaml
  dev_scripts/chemenv/get_plane_permutations_optimized.py
  pymatgen/analysis/bond_dissociation.py
  pymatgen/analysis/chemenv/connectivity/connected_components.py
  pymatgen/analysis/chemenv/connectivity/structure_connectivity.py
  pymatgen/analysis/chemenv/coordination_environments/chemenv_strategies.py
  pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py
  pymatgen/analysis/chemenv/coordination_environments/structure_environments.py
  pymatgen/analysis/chemenv/utils/coordination_geometry_utils.py
  pymatgen/analysis/chemenv/utils/graph_utils.py
  pymatgen/analysis/functional_groups.py
  pymatgen/analysis/gb/grain.py
  pymatgen/analysis/local_env.py
  pymatgen/analysis/magnetism/heisenberg.py
  pymatgen/analysis/tests/test_phase_diagram.py
  pymatgen/command_line/chargemol_caller.py
  pymatgen/core/structure.py
  pymatgen/core/xcfunc.py
  pymatgen/electronic_structure/cohp.py
  pymatgen/electronic_structure/plotter.py
  pymatgen/entries/compatibility.py
  pymatgen/io/abinit/pseudos.py
  pymatgen/io/cp2k/inputs.py
  pymatgen/io/cp2k/outputs.py
  pymatgen/io/exciting/inputs.py
  pymatgen/io/lammps/data.py
  pymatgen/io/lammps/tests/test_data.py
  pymatgen/io/lobster/inputs.py
  pymatgen/io/lobster/lobsterenv.py
  pymatgen/io/lobster/outputs.py
  pymatgen/io/qchem/outputs.py
  pymatgen/io/res.py
  pymatgen/io/vasp/outputs.py
  pymatgen/io/vasp/sets.py
  pymatgen/io/vasp/tests/test_outputs.py
  pymatgen/io/wannier90.py
  pymatgen/phonon/plotter.py
  pymatgen/symmetry/analyzer.py
  pymatgen/symmetry/kpath.py
  pymatgen/util/string.py
  pyproject.toml
Labels: qa

#2942 only return unique point group operations
  pymatgen/symmetry/analyzer.py
  pymatgen/symmetry/tests/test_analyzer.py
  test_files/.pytest-split-durations
Labels: enhancement, symmetry

#2980 Enable ruff rule sets ISC + ICN
  dev_scripts/chemenv/get_plane_permutations_optimized.py
  pymatgen/analysis/chemenv/connectivity/tests/test_connected_components.py
  pymatgen/analysis/chemenv/coordination_environments/structure_environments.py
  pymatgen/analysis/chemenv/utils/tests/test_graph_utils.py
  pymatgen/analysis/graphs.py
  pymatgen/analysis/molecule_matcher.py
  pymatgen/analysis/phase_diagram.py
  pymatgen/analysis/pourbaix_diagram.py
  pymatgen/analysis/tests/test_phase_diagram.py
  pymatgen/core/trajectory.py
  pymatgen/electronic_structure/boltztrap.py
  pymatgen/electronic_structure/plotter.py
  pymatgen/electronic_structure/tests/test_bandstructure.py
  pymatgen/entries/correction_calculator.py
  pymatgen/io/common.py
  pymatgen/io/cp2k/inputs.py
  pymatgen/io/cp2k/outputs.py
  pymatgen/io/cp2k/sets.py
  pymatgen/io/gaussian.py
  pymatgen/io/lammps/inputs.py
  pymatgen/io/lammps/tests/test_data.py
  pymatgen/io/lobster/tests/test_lobster.py
  pymatgen/io/nwchem.py
  pymatgen/io/qchem/outputs.py
  pymatgen/io/qchem/sets.py
  pymatgen/io/vasp/inputs.py
  pymatgen/io/vasp/outputs.py
  pymatgen/io/xr.py
  pymatgen/io/xyz.py
  pymatgen/io/zeopp.py
  pymatgen/util/plotting.py
  pymatgen/util/provenance.py
  pymatgen/util/tests/test_convergence.py
  pyproject.toml
  setup.py
Labels: qa

#2982 `ruff` enable `flake8-pyi` + `flake8-ret`
  CHANGES.rst
  pymatgen/analysis/local_env.py
  pymatgen/analysis/magnetism/heisenberg.py
  pymatgen/analysis/phase_diagram.py
  pymatgen/analysis/tests/test_wulff.py
  pymatgen/core/trajectory.py
  pymatgen/electronic_structure/cohp.py
  pymatgen/electronic_structure/dos.py
  pymatgen/electronic_structure/tests/test_plotter.py
  pymatgen/entries/mixing_scheme.py
  pymatgen/entries/tests/test_mixing_scheme.py
  pymatgen/io/cif.py
  pymatgen/io/cp2k/outputs.py
  pymatgen/io/cp2k/sets.py
  pymatgen/io/lammps/inputs.py
  pymatgen/io/pwscf.py
  pymatgen/io/qchem/inputs.py
  pymatgen/io/qchem/sets.py
  pymatgen/io/res.py
  pymatgen/io/tests/test_adf.py
  pymatgen/io/vasp/optics.py
  pymatgen/phonon/plotter.py
  pymatgen/phonon/thermal_displacements.py
  pymatgen/util/graph_hashing.py
  pyproject.toml
Labels: qa

#2983 Fix for memory leak in pbc_shortest_vectors
  pymatgen/util/coord_cython.pyx
Labels: awaiting user, fix, memory

#2981 Drop deprecated SubstrateAnalyzer + ZSLGenerator reexports
  pymatgen/analysis/interfaces/substrate_analyzer.py
  pymatgen/analysis/pourbaix_diagram.py
  pymatgen/analysis/substrate_analyzer.py
  pymatgen/analysis/tests/test_pourbaix_diagram.py
  pymatgen/io/abinit/pseudos.py
  pymatgen/io/lammps/inputs.py
  pymatgen/io/tests/test_zeopp.py
  pymatgen/io/vasp/outputs.py
  pymatgen/io/vasp/sets.py
  pymatgen/io/zeopp.py
  pymatgen/transformations/advanced_transformations.py
  pymatgen/transformations/standard_transformations.py
  pymatgen/util/convergence.py
  pymatgen/util/typing.py
Labels: breaking

#2987 Doc strings
  .pre-commit-config.yaml
  dev_scripts/chemenv/get_plane_permutations_optimized.py
  dev_scripts/chemenv/test_algos.py
  dev_scripts/chemenv/view_environment.py
  pymatgen/analysis/bond_valence.py
  pymatgen/analysis/chemenv/connectivity/connected_components.py
  pymatgen/analysis/chemenv/coordination_environments/structure_environments.py
  pymatgen/analysis/graphs.py
  pymatgen/analysis/local_env.py
  pymatgen/analysis/surface_analysis.py
  pymatgen/analysis/xas/spectrum.py
  pymatgen/cli/pmg_config.py
  pymatgen/core/composition.py
  pymatgen/core/interface.py
  pymatgen/core/lattice.py
  pymatgen/core/molecular_orbitals.py
  pymatgen/core/spectrum.py
  pymatgen/core/structure.py
  pymatgen/core/surface.py
  pymatgen/core/tensors.py
  pymatgen/core/trajectory.py
  pymatgen/core/units.py
  pymatgen/electronic_structure/plotter.py
  pymatgen/io/abinit/abiobjects.py
  pymatgen/io/abinit/inputs.py
  pymatgen/io/abinit/pseudos.py
  pymatgen/io/adf.py
  pymatgen/io/cif.py
  pymatgen/io/core.py
  pymatgen/io/cp2k/inputs.py
  pymatgen/io/packmol.py
  pymatgen/io/pwscf.py
  pymatgen/transformations/advanced_transformations.py
  pymatgen/transformations/site_transformations.py
  pymatgen/transformations/standard_transformations.py
  pymatgen/transformations/transformation_abc.py
  pymatgen/util/num.py
  pyproject.toml
Labels: docs

#2989 Suspected Typo Fix in `pymatgen.io.vasp.optics`
  pymatgen/io/vasp/optics.py
  pymatgen/io/vasp/tests/test_optics.py
Labels: io, fix

#2990 Enable ruff doc rules in CI
  .pre-commit-config.yaml
  docs_rst/conf-normal.py
  docs_rst/conf.py
  pymatgen/alchemy/materials.py
  pymatgen/alchemy/transmuters.py
  pymatgen/analysis/structure_matcher.py
  pymatgen/apps/battery/analyzer.py
  pymatgen/apps/battery/plotter.py
  pymatgen/apps/borg/queen.py
  pymatgen/cli/pmg_analyze.py
  pymatgen/command_line/chargemol_caller.py
  pymatgen/command_line/gulp_caller.py
  pymatgen/core/ion.py
  pymatgen/core/libxcfunc.py
  pymatgen/electronic_structure/bandstructure.py
  pymatgen/electronic_structure/boltztrap.py
  pymatgen/electronic_structure/boltztrap2.py
  pymatgen/electronic_structure/cohp.py
  pymatgen/electronic_structure/dos.py
  pymatgen/electronic_structure/plotter.py
  pymatgen/electronic_structure/tests/test_boltztrap.py
  pymatgen/entries/compatibility.py
  pymatgen/ext/cod.py
  pymatgen/ext/matproj.py
  pymatgen/io/vasp/outputs.py
  pymatgen/symmetry/analyzer.py
  pymatgen/symmetry/groups.py
  pymatgen/symmetry/kpath.py
  pymatgen/symmetry/maggroups.py
  pyproject.toml
Labels: qa, docs

#2995 Re-export `SiteCollection` + `DummySpecies` from `pymatgen.core`
  dev_scripts/regen_libxcfunc.py
  pymatgen/alchemy/filters.py
  pymatgen/analysis/energy_models.py
  pymatgen/analysis/local_env.py
  pymatgen/analysis/magnetism/heisenberg.py
  pymatgen/analysis/structure_prediction/substitution_probability.py
  pymatgen/apps/borg/hive.py
  pymatgen/cli/pmg_config.py
  pymatgen/core/__init__.py
  pymatgen/core/tensors.py
  pymatgen/core/tests/test_units.py
  pymatgen/ext/matproj.py
  pymatgen/io/abinit/abiobjects.py
  pymatgen/io/abinit/abitimer.py
  pymatgen/io/abinit/inputs.py
  pymatgen/io/abinit/netcdf.py
  pymatgen/io/abinit/pseudos.py
  pymatgen/io/abinit/tests/test_netcdf.py
  pymatgen/io/cif.py
  pymatgen/io/cp2k/inputs.py
  pymatgen/io/fiesta.py
  pymatgen/io/lammps/outputs.py
  pymatgen/io/qchem/outputs.py
  pymatgen/phonon/bandstructure.py
  pymatgen/transformations/advanced_transformations.py
Labels: imports

#2998 `Species` parse oxi state from symbol str
  dev_scripts/update_pt_data.py
  pymatgen/core/periodic_table.py
  pymatgen/core/tests/test_periodic_table.py
  test_files/.pytest-split-durations
Labels: enhancement

#3002 Add LightStructureEnvironments.from_structure_environments() fallback value if `ce_and_neighbors` is None
  pymatgen/analysis/chemenv/coordination_environments/structure_environments.py
  pymatgen/analysis/chemenv/coordination_environments/tests/test_structure_environments.py
  test_files/mp-554015.json.gz
Labels: fix, analysis

#3003 Support writing structures to compressed JSON (.json.gz .json.bz2 .json.xz .json.lzma)
  pymatgen/core/structure.py
  pymatgen/core/tests/test_structure.py
  pymatgen/ext/tests/test_optimade.py
Labels: enhancement, io

#3004 Lookup `MPRester` API key in settings if `None` provided as arg
  pymatgen/ext/matproj.py
  pymatgen/ext/tests/test_matproj.py
Labels: fix, api

#3005 Update `.pytest-split-durations`
  .github/workflows/test.yml
  pymatgen/analysis/chemenv/coordination_environments/structure_environments.py
  pymatgen/analysis/graphs.py
  pymatgen/analysis/local_env.py
  pymatgen/analysis/tests/test_graphs.py
  pymatgen/core/tests/test_structure.py
  pymatgen/ext/tests/test_optimade.py
  pyproject.toml
  test_files/.pytest-split-durations
Labels: tests, fix, api

#3010 Clean up
  docs_rst/conf-normal.py
  pymatgen/alchemy/tests/test_materials.py
  pymatgen/analysis/bond_valence.py
  pymatgen/analysis/chemenv/coordination_environments/chemenv_strategies.py
  pymatgen/analysis/chemenv/coordination_environments/structure_environments.py
  pymatgen/analysis/interfaces/substrate_analyzer.py
  pymatgen/analysis/local_env.py
  pymatgen/analysis/magnetism/analyzer.py
  pymatgen/analysis/tests/test_adsorption.py
  pymatgen/command_line/enumlib_caller.py
  pymatgen/command_line/tests/test_gulp_caller.py
  pymatgen/core/structure.py
  pymatgen/core/tests/test_structure.py
  pymatgen/electronic_structure/boltztrap.py
  pymatgen/electronic_structure/cohp.py
  pymatgen/entries/mixing_scheme.py
  pymatgen/io/abinit/abitimer.py
  pymatgen/io/abinit/pseudos.py
  pymatgen/io/cif.py
  pymatgen/io/lobster/lobsterenv.py
  pymatgen/io/qchem/tests/test_inputs.py
  pymatgen/io/res.py
  pymatgen/io/tests/test_babel.py
  pymatgen/io/tests/test_zeopp.py
  pymatgen/io/vasp/sets.py
  pymatgen/io/xtb/inputs.py
  pymatgen/io/xtb/tests/test_outputs.py
  pymatgen/io/zeopp.py
  pymatgen/symmetry/groups.py
  pymatgen/symmetry/tests/test_groups.py
  pymatgen/transformations/advanced_transformations.py
  pymatgen/transformations/site_transformations.py
  pymatgen/transformations/standard_transformations.py
  pyproject.toml
Labels: qa

#3012 Fix `ValueError` when `structure.selective_dynamics` has type `np.array`
  pymatgen/io/ase.py
  pymatgen/io/lammps/data.py
  pymatgen/io/tests/test_ase.py
Labels: io, fix

#3017 MaterialsProjectCompatibility issue deprecation warning
  pymatgen/core/lattice.py
  pymatgen/core/sites.py
  pymatgen/core/structure.py
  pymatgen/entries/compatibility.py
  pymatgen/symmetry/structure.py
  pymatgen/symmetry/tests/test_analyzer.py
Labels: docs

#3019 Tweak variable names
  pymatgen/analysis/chemenv/coordination_environments/coordination_geometries.py
  pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py
  pymatgen/analysis/graphs.py
  pymatgen/analysis/phase_diagram.py
  pymatgen/analysis/surface_analysis.py
  pymatgen/command_line/tests/test_mcsqs_caller.py
  pymatgen/core/composition.py
  pymatgen/core/ion.py
  pymatgen/core/operations.py
  pymatgen/core/periodic_table.py
  pymatgen/core/structure.py
  pymatgen/core/tests/test_composition.py
  pymatgen/core/tests/test_ion.py
  pymatgen/core/tests/test_operations.py
  pymatgen/core/tests/test_structure.py
  pymatgen/electronic_structure/plotter.py
  pymatgen/io/lmto.py
  pymatgen/io/lobster/lobsterenv.py
  pymatgen/symmetry/analyzer.py
  pymatgen/symmetry/structure.py
  pymatgen/transformations/tests/test_advanced_transformations.py
  pymatgen/util/string.py
  pymatgen/util/tests/test_string.py
Labels: housekeeping

#3020 Unignore `ruff` `PD011`
  pymatgen/entries/mixing_scheme.py
  pymatgen/io/abinit/abitimer.py
  pymatgen/io/abinit/pseudos.py
  pymatgen/io/cp2k/inputs.py
  pymatgen/io/cp2k/outputs.py
  pymatgen/io/cp2k/sets.py
  pymatgen/io/cp2k/tests/test_inputs.py
  pymatgen/io/cp2k/tests/test_sets.py
  pymatgen/io/lammps/data.py
  pymatgen/io/lammps/tests/test_data.py
  pymatgen/io/lammps/tests/test_generators.py
  pyproject.toml
Labels: qa, housekeeping
