Repository materialsproject/pymatgen, pull requests merged in 2024-03, with the labels that each got.

#3664 Fix RuntimeError triggered in CI of downstream packages
  pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py
  pymatgen/analysis/chemenv/utils/coordination_geometry_utils.py
  pymatgen/analysis/elasticity/elastic.py
  pymatgen/analysis/ewald.py
  pymatgen/analysis/graphs.py
  pymatgen/analysis/interface_reactions.py
  pymatgen/analysis/local_env.py
  pymatgen/analysis/molecule_matcher.py
  pymatgen/analysis/molecule_structure_comparator.py
  pymatgen/analysis/phase_diagram.py
  pymatgen/command_line/bader_caller.py
  pymatgen/core/structure.py
  pymatgen/entries/computed_entries.py
  pymatgen/io/cif.py
  pymatgen/io/cp2k/utils.py
  pymatgen/io/lobster/outputs.py
  pymatgen/io/vasp/optics.py
  pymatgen/io/vasp/outputs.py
  pymatgen/io/vasp/sets.py
  pymatgen/symmetry/analyzer.py
  pymatgen/transformations/advanced_transformations.py
  pymatgen/vis/structure_vtk.py
  tests/analysis/test_interface_reactions.py
  tests/command_line/test_bader_caller.py
  tests/io/vasp/test_outputs.py
Labels: fix, ci, urgent

#3675 Migrate CI dependency installation from `pip` to `uv`
  .github/workflows/release.yml
  .github/workflows/test.yml
  pymatgen/transformations/advanced_transformations.py
  tests/core/test_structure.py
  tests/transformations/test_advanced_transformations.py
Labels: performance, ci, pkg

#3676 Add hash for BalancedReaction
  pymatgen/analysis/pourbaix_diagram.py
  pymatgen/analysis/reaction_calculator.py
  pymatgen/apps/battery/conversion_battery.py
  tests/analysis/test_reaction_calculator.py
Labels: qa, analysis

#3679 Fix `phonopy.get_pmg_structure` `site_properties` key for magmoms
  pymatgen/io/phonopy.py
  tests/io/test_phonopy.py
Labels: io, fix, magmoms, phonon

#3688 Generalize fatband plots from Lobster
  pymatgen/io/lobster/outputs.py
  tests/files/cohp/Fatband_SiO2/Test_p_x/POSCAR
  tests/io/lobster/test_inputs.py
Labels: enhancement, data viz

#3689 Improve Bandoverlaps parser
  pymatgen/io/lobster/outputs.py
  tests/io/lobster/test_inputs.py
Labels: io, fix, lobster

#3690 `os.path.(exists->isfile)`
  pymatgen/analysis/ewald.py
  pymatgen/analysis/local_env.py
  pymatgen/analysis/phase_diagram.py
  pymatgen/analysis/surface_analysis.py
  pymatgen/analysis/wulff.py
  pymatgen/cli/feff_plot_dos.py
  pymatgen/cli/pmg_analyze.py
  pymatgen/cli/pmg_config.py
  pymatgen/cli/pmg_plot.py
  pymatgen/cli/pmg_structure.py
  pymatgen/command_line/chargemol_caller.py
  pymatgen/command_line/critic2_caller.py
  pymatgen/command_line/mcsqs_caller.py
  pymatgen/core/structure.py
  pymatgen/core/surface.py
  pymatgen/electronic_structure/boltztrap.py
  pymatgen/electronic_structure/dos.py
  pymatgen/io/abinit/inputs.py
  pymatgen/io/abinit/pseudos.py
  pymatgen/io/cp2k/outputs.py
  pymatgen/io/cp2k/sets.py
  pymatgen/io/cp2k/utils.py
  pymatgen/io/feff/inputs.py
  pymatgen/io/fiesta.py
  pymatgen/io/lammps/inputs.py
  pymatgen/io/lammps/utils.py
  pymatgen/io/qchem/outputs.py
  pymatgen/io/vasp/inputs.py
  pymatgen/io/vasp/outputs.py
  pymatgen/io/vasp/sets.py
  pymatgen/io/xcrysden.py
  tests/analysis/chemenv/coordination_environments/test_structure_environments.py
  tests/analysis/test_adsorption.py
  tests/analysis/test_local_env.py
  tests/core/test_surface.py
  tests/io/feff/test_inputs.py
  tests/io/lammps/test_inputs.py
  tests/io/test_packmol.py
  tests/io/test_phonopy.py
  tests/io/test_xyz.py
  tests/test_cli.py
  tests/test_pkg.py
Labels: qa

#2926 Plotting of Multicenter COBIs
  pymatgen/electronic_structure/cohp.py
  pymatgen/electronic_structure/plotter.py
  pymatgen/io/common.py
  pymatgen/io/lobster/outputs.py
  tests/electronic_structure/test_cohp.py
  tests/files/cohp/COBICAR.lobster.B2H6.spin
  tests/files/cohp/COBICAR.lobster.B2H6.spin.average.2
  tests/files/cohp/COBICAR.lobster.GeTe
  tests/files/cohp/COBICAR.lobster.GeTe.multi.orbitalwise
  tests/files/cohp/COBICAR.lobster.GeTe.multi.orbitalwise.full
  tests/files/cohp/COBICAR.lobster.GeTe_4center
  tests/files/cohp/POSCAR.B2H6
  tests/files/cohp/POSCAR.GeTe
  tests/files/cohp/POSCAR.lobster
  tests/files/cohp/cobi.json
  tests/files/cohp/cohp.json
  tests/io/lobster/test_inputs.py
Labels: enhancement, io, lobster

#3697 Prevent GitHub Actions from running document related CIs on forks
  .github/workflows/jekyll-gh-pages.yml
  .github/workflows/test.yml
  pymatgen/cli/pmg_config.py
Labels: contributing, ci, dx

#3704 Support appending vectors to positions in XSF format
  pymatgen/io/xcrysden.py
  tests/io/test_xcrysden.py
Labels: enhancement, io, phonon

#3706 Return `self` from `Structure` methods `replace`, `substitute`, `remove_species`, `remove_sites`
  pymatgen/core/structure.py
  tests/core/test_structure.py
  tests/files/.pytest-split-durations
Labels: api, ux, core

#3707 `Self` return type on `Lattice` methods
  .github/workflows/jekyll-gh-pages.yml
  .github/workflows/test.yml
  pymatgen/core/lattice.py
  pymatgen/util/typing.py
  tests/core/test_lattice.py
  tests/util/test_typing.py
Labels: types

#3710 Convert some `staticmethod` to `classmethod`
  pymatgen/alchemy/transmuters.py
  pymatgen/analysis/graphs.py
  pymatgen/core/operations.py
  pymatgen/io/abinit/pseudos.py
  pymatgen/io/babel.py
  pymatgen/io/cp2k/inputs.py
  pymatgen/io/feff/inputs.py
  pymatgen/io/pwmat/inputs.py
  pymatgen/io/vasp/inputs.py
  pymatgen/phonon/thermal_displacements.py
  pymatgen/transformations/advanced_transformations.py
  pymatgen/transformations/standard_transformations.py
  pymatgen/util/provenance.py
Labels: fix, qa

#3703 Define `needs_u_correction(comp: CompositionLike) -> set[str]` utility function
  .pre-commit-config.yaml
  pymatgen/entries/compatibility.py
  tests/entries/test_compatibility.py
Labels: enhancement, tests, mixing-schemes

#3700 Add more flexibility to `PhononDOSPlotter` and `PhononBSPlotter`
  pymatgen/phonon/plotter.py
  tests/phonon/test_plotter.py
Labels: enhancement, data viz, phonon

#3713 Clean up tests
  pymatgen/io/lmto.py
  pymatgen/io/nwchem.py
  tests/analysis/elasticity/test_elastic.py
  tests/analysis/ferroelectricity/test_polarization.py
  tests/analysis/test_graphs.py
  tests/analysis/test_local_env.py
  tests/core/test_interface.py
  tests/core/test_lattice.py
  tests/core/test_surface.py
  tests/core/test_trajectory.py
  tests/core/test_units.py
  tests/electronic_structure/test_boltztrap.py
  tests/electronic_structure/test_plotter.py
  tests/ext/test_matproj.py
  tests/io/abinit/test_inputs.py
  tests/io/lobster/test_inputs.py
  tests/io/test_pwscf.py
  tests/io/vasp/test_outputs.py
  tests/symmetry/test_analyzer.py
  tests/transformations/test_standard_transformations.py
Labels: tests, qa, housekeeping

#3727 Add a fix for if a parameter is None in AimsControlIn
  pymatgen/io/aims/inputs.py
  tests/io/aims/test_aims_inputs.py
Labels: io, fix

#3728 Replace general `raise Exception` and add missing `raise` keyword
  pymatgen/analysis/chemenv/coordination_environments/coordination_geometries.py
  pymatgen/analysis/molecule_matcher.py
  pymatgen/apps/battery/battery_abc.py
  pymatgen/core/operations.py
  pymatgen/electronic_structure/bandstructure.py
  pymatgen/io/adf.py
  pymatgen/io/cif.py
  pymatgen/io/vasp/outputs.py
  pymatgen/transformations/advanced_transformations.py
Labels: qa, ux
