Repository materialsproject/pymatgen, pull requests merged in 2024-05, with the labels that each got.

#3685 Officially support Python 3.12 and test in CI
  .github/workflows/release.yml
  .github/workflows/test.yml
  dev_scripts/chemenv/get_plane_permutations_optimized.py
  dev_scripts/chemenv/plane_multiplicity.py
  pymatgen/alchemy/materials.py
  pymatgen/alchemy/transmuters.py
  pymatgen/analysis/structure_prediction/substitutor.py
  pymatgen/io/lobster/inputs.py
  pymatgen/io/vasp/outputs.py
  setup.py
  tests/alchemy/test_materials.py
  tests/io/lobster/test_inputs.py
  tests/io/test_shengbte.py
  tests/io/vasp/test_outputs.py
Labels: compatability, ci, pkg

#3797 Homogenize return type of `Lattice.get_points_in_sphere` to always be `np.array`(s)
  pymatgen/core/lattice.py
  tests/core/test_lattice.py
Labels: fix, core

#3774 Make `Beautifulsoup` optional
  dev_scripts/update_pt_data.py
  pymatgen/io/vasp/help.py
  requirements-optional.txt
  requirements.txt
Labels: dependencies, fix, imports, pkg

#3798 Fix overlayed subplots in `BSPlotterProjected.get_projected_plots_dots()`
  pymatgen/apps/borg/queen.py
  pymatgen/electronic_structure/bandstructure.py
  pymatgen/electronic_structure/plotter.py
  pymatgen/phonon/plotter.py
  pymatgen/symmetry/kpath.py
  pymatgen/transformations/site_transformations.py
  tests/electronic_structure/test_bandstructure.py
  tests/electronic_structure/test_plotter.py
Labels: fix, data viz, electronic structure

#3800 More type annotations
  dev_scripts/potcar_scrambler.py
  dev_scripts/update_pt_data.py
  pymatgen/alchemy/filters.py
  pymatgen/analysis/chemenv/coordination_environments/coordination_geometries.py
  pymatgen/analysis/chempot_diagram.py
  pymatgen/analysis/elasticity/elastic.py
  pymatgen/analysis/ewald.py
  pymatgen/analysis/ferroelectricity/polarization.py
  pymatgen/analysis/molecule_structure_comparator.py
  pymatgen/analysis/nmr.py
  pymatgen/analysis/pourbaix_diagram.py
  pymatgen/analysis/structure_matcher.py
  pymatgen/analysis/structure_prediction/dopant_predictor.py
  pymatgen/analysis/structure_prediction/substitution_probability.py
  pymatgen/analysis/structure_prediction/substitutor.py
  pymatgen/analysis/surface_analysis.py
  pymatgen/analysis/thermochemistry.py
  pymatgen/apps/battery/battery_abc.py
  pymatgen/apps/battery/insertion_battery.py
  pymatgen/apps/borg/hive.py
  pymatgen/command_line/bader_caller.py
  pymatgen/command_line/chargemol_caller.py
  pymatgen/command_line/critic2_caller.py
  pymatgen/core/interface.py
  pymatgen/core/lattice.py
  pymatgen/core/operations.py
  pymatgen/core/spectrum.py
  pymatgen/core/structure.py
  pymatgen/core/surface.py
  pymatgen/electronic_structure/boltztrap.py
  pymatgen/entries/correction_calculator.py
  pymatgen/ext/matproj_legacy.py
  pymatgen/io/abinit/abiobjects.py
  pymatgen/io/abinit/pseudos.py
  pymatgen/io/adf.py
  pymatgen/io/cif.py
  pymatgen/io/common.py
  pymatgen/io/feff/inputs.py
  pymatgen/io/feff/outputs.py
  pymatgen/io/icet.py
  pymatgen/io/lammps/outputs.py
  pymatgen/io/lobster/outputs.py
  pymatgen/io/nwchem.py
  pymatgen/io/openff.py
  pymatgen/io/phonopy.py
  pymatgen/io/pwscf.py
  pymatgen/io/shengbte.py
  pymatgen/io/vasp/help.py
  pymatgen/io/vasp/inputs.py
  pymatgen/phonon/bandstructure.py
  pymatgen/phonon/gruneisen.py
  pymatgen/symmetry/settings.py
  pymatgen/symmetry/structure.py
  pymatgen/transformations/advanced_transformations.py
  pymatgen/transformations/site_transformations.py
  pymatgen/transformations/standard_transformations.py
  pymatgen/transformations/transformation_abc.py
  pymatgen/util/provenance.py
  tests/core/test_interface.py
  tests/transformations/test_advanced_transformations.py
Labels: linting, types

#3801 Fix `_get_dipole_info` for DDEC6 `ChargemolAnalysis` and add test case
  pymatgen/command_line/chargemol_caller.py
  tests/command_line/test_chargemol_caller.py
Labels: fix, charge

#3804 Add `is_radioactive` property to Element class
  pymatgen/core/composition.py
  pymatgen/core/periodic_table.py
  tests/core/test_periodic_table.py
Labels: enhancement, core

#3806 mixing scheme: change default for verbose
  pymatgen/entries/mixing_scheme.py
Labels: ux

#3808 `ruff` 0.4.3 auto-fixes
  .pre-commit-config.yaml
  pymatgen/analysis/eos.py
  pymatgen/analysis/transition_state.py
  pymatgen/core/sites.py
  pymatgen/electronic_structure/plotter.py
  pymatgen/io/abinit/inputs.py
  pymatgen/io/abinit/pseudos.py
  pymatgen/io/aims/inputs.py
  pymatgen/io/ase.py
  pymatgen/io/feff/inputs.py
  pymatgen/io/lobster/inputs.py
  pymatgen/io/pwmat/inputs.py
  pymatgen/io/xcrysden.py
  pymatgen/util/provenance.py
  pymatgen/util/testing/aims.py
  pymatgen/vis/structure_vtk.py
  tests/analysis/test_interface_reactions.py
  tests/analysis/test_molecule_matcher.py
Labels: linting

#3810 `Cp2kOutput.parse_initial_structure()` use regex for line matching to allow arbitrary white space between Atom/Kind/Element/...
  pymatgen/io/cp2k/outputs.py
  tests/files/io/cp2k/cp2k.out
Labels: io, fix, cp2k

#3812 Add a `from_ase_atoms()` method to `Structure`
  pymatgen/core/structure.py
  tests/core/test_structure.py
Labels: enhancement, api, ase

#3813 Re-enable some useful `ruff` rules
  pymatgen/analysis/chemenv/coordination_environments/chemenv_strategies.py
  pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py
  pymatgen/analysis/chemenv/utils/chemenv_config.py
  pymatgen/analysis/chemenv/utils/defs_utils.py
  pymatgen/analysis/chemenv/utils/func_utils.py
  pymatgen/analysis/diffraction/tem.py
  pymatgen/analysis/eos.py
  pymatgen/analysis/graphs.py
  pymatgen/analysis/local_env.py
  pymatgen/analysis/magnetism/analyzer.py
  pymatgen/analysis/molecule_structure_comparator.py
  pymatgen/analysis/nmr.py
  pymatgen/command_line/mcsqs_caller.py
  pymatgen/core/composition.py
  pymatgen/core/xcfunc.py
  pymatgen/electronic_structure/dos.py
  pymatgen/ext/matproj.py
  pymatgen/ext/optimade.py
  pymatgen/io/abinit/abiobjects.py
  pymatgen/io/abinit/inputs.py
  pymatgen/io/abinit/pseudos.py
  pymatgen/io/adf.py
  pymatgen/io/aims/parsers.py
  pymatgen/io/icet.py
  pymatgen/io/nwchem.py
  pymatgen/io/pwscf.py
  pymatgen/io/qchem/outputs.py
  pymatgen/io/res.py
  pymatgen/io/vasp/inputs.py
  pymatgen/phonon/plotter.py
  pymatgen/symmetry/groups.py
  pymatgen/util/provenance.py
  pyproject.toml
Labels: linting

#3823 Adapt to the latest version of PWmat output file
  pymatgen/io/pwmat/inputs.py
  tests/files/io/pwmat/MOVEMENT.lzma
  tests/io/pwmat/test_inputs.py
Labels: enhancement, io

#3829 Add types for `core.(molecular_orbitals|operations|sites|spectrum|tensor|xcfunc)`
  pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py
  pymatgen/analysis/chemenv/utils/coordination_geometry_utils.py
  pymatgen/analysis/ferroelectricity/polarization.py
  pymatgen/analysis/magnetism/analyzer.py
  pymatgen/command_line/gulp_caller.py
  pymatgen/command_line/mcsqs_caller.py
  pymatgen/core/composition.py
  pymatgen/core/ion.py
  pymatgen/core/lattice.py
  pymatgen/core/molecular_orbitals.py
  pymatgen/core/operations.py
  pymatgen/core/periodic_table.py
  pymatgen/core/sites.py
  pymatgen/core/spectrum.py
  pymatgen/core/structure.py
  pymatgen/core/tensors.py
  pymatgen/core/xcfunc.py
  pymatgen/io/cp2k/inputs.py
  pymatgen/io/cssr.py
  pymatgen/io/fiesta.py
  pymatgen/io/qchem/outputs.py
  pymatgen/io/xr.py
  pymatgen/io/zeopp.py
  pymatgen/phonon/bandstructure.py
  pymatgen/transformations/advanced_transformations.py
  tests/core/test_structure.py
  tests/core/test_trajectory.py
  tests/core/test_units.py
  tests/io/test_cif.py
Labels: housekeeping, types

#3827 Guard `TYPE_CHECKING` only imports
  pymatgen/alchemy/materials.py
  pymatgen/alchemy/transmuters.py
  pymatgen/analysis/chemenv/coordination_environments/coordination_geometries.py
  pymatgen/analysis/chemenv/utils/coordination_geometry_utils.py
  pymatgen/analysis/elasticity/elastic.py
  pymatgen/analysis/elasticity/strain.py
  pymatgen/analysis/ewald.py
  pymatgen/analysis/interface_reactions.py
  pymatgen/analysis/magnetism/jahnteller.py
  pymatgen/analysis/phase_diagram.py
  pymatgen/analysis/pourbaix_diagram.py
  pymatgen/analysis/structure_matcher.py
  pymatgen/cli/pmg_config.py
  pymatgen/command_line/bader_caller.py
  pymatgen/core/interface.py
  pymatgen/core/periodic_table.py
  pymatgen/core/structure.py
  pymatgen/core/units.py
  pymatgen/electronic_structure/bandstructure.py
  pymatgen/electronic_structure/boltztrap.py
  pymatgen/electronic_structure/cohp.py
  pymatgen/entries/__init__.py
  pymatgen/entries/compatibility.py
  pymatgen/entries/computed_entries.py
  pymatgen/entries/entry_tools.py
  pymatgen/ext/matproj_legacy.py
  pymatgen/io/aims/inputs.py
  pymatgen/io/aims/outputs.py
  pymatgen/io/aims/parsers.py
  pymatgen/io/aims/sets/base.py
  pymatgen/io/aims/sets/bs.py
  pymatgen/io/aims/sets/core.py
  pymatgen/io/cif.py
  pymatgen/io/cp2k/inputs.py
  pymatgen/io/lammps/data.py
  pymatgen/io/lobster/inputs.py
  pymatgen/io/lobster/outputs.py
  pymatgen/io/pwscf.py
  pymatgen/io/qchem/inputs.py
  pymatgen/io/qchem/outputs.py
  pymatgen/io/qchem/sets.py
  pymatgen/io/res.py
  pymatgen/io/shengbte.py
  pymatgen/io/vasp/outputs.py
  pymatgen/io/vasp/sets.py
  pymatgen/phonon/bandstructure.py
  pymatgen/phonon/plotter.py
  pymatgen/phonon/thermal_displacements.py
  pymatgen/symmetry/analyzer.py
  pymatgen/symmetry/groups.py
  pymatgen/symmetry/kpath.py
  pymatgen/util/plotting.py
  pymatgen/util/testing/__init__.py
  pymatgen/vis/structure_vtk.py
  tests/util/test_typing.py
Labels: types

#3831 Move test structures out of `util` directory
  pymatgen/util/testing/__init__.py
  tests/files/structures/BaNiO3.json
  tests/files/structures/CsCl.json
  tests/files/structures/Graphite.json
  tests/files/structures/He_BCC.json
  tests/files/structures/K2O2.json
  tests/files/structures/La2CoO4F.json
  tests/files/structures/Li10GeP2S12.json
  tests/files/structures/Li2O.json
  tests/files/structures/Li2O2.json
  tests/files/structures/Li3V2(PO4)3.json
  tests/files/structures/LiFePO4.json
  tests/files/structures/NaFePO4.json
  tests/files/structures/Pb2TiZrO6.json
  tests/files/structures/Si.json
  tests/files/structures/SiO2.json
  tests/files/structures/Si_SiO2_Interface.json
  tests/files/structures/Sn.json
  tests/files/structures/SrTiO3.json
  tests/files/structures/TiO2.json
  tests/files/structures/TlBiSe2.json
  tests/files/structures/VO2.json
Labels: tests, housekeeping

#3832 Improve type annotations for `core.(trajectory/units)`
  pymatgen/core/trajectory.py
  pymatgen/core/units.py
  tests/core/test_trajectory.py
  tests/core/test_units.py
Labels: tests, linting, types

#3846 `pandas.read_csv`: replace deprecated `delim_whitespace=True` with `sep="\s+"`
  pymatgen/io/lammps/data.py
  pymatgen/io/lammps/outputs.py
  pymatgen/io/xyz.py
  pymatgen/util/provenance.py
Labels: ux, deprecation, lammps

#3776 Add type annotations for `io.vasp.outputs`
  pymatgen/core/trajectory.py
  pymatgen/entries/computed_entries.py
  pymatgen/io/lobster/outputs.py
  pymatgen/io/vasp/optics.py
  pymatgen/io/vasp/outputs.py
  pymatgen/io/vasp/sets.py
  pyproject.toml
Labels: io, vasp, types
