Repository materialsproject/pymatgen, pull requests merged in 2024-04, with the labels that each got.

#3732 Test `EntrySet.ground_states` and CIF writing in `NEBSet.write_input`
  pymatgen/analysis/adsorption.py
  pymatgen/analysis/bond_valence.py
  pymatgen/analysis/chemenv/utils/coordination_geometry_utils.py
  pymatgen/analysis/ferroelectricity/polarization.py
  pymatgen/analysis/local_env.py
  pymatgen/analysis/phase_diagram.py
  pymatgen/analysis/structure_matcher.py
  pymatgen/analysis/surface_analysis.py
  pymatgen/core/lattice.py
  pymatgen/core/operations.py
  pymatgen/core/structure.py
  pymatgen/core/surface.py
  pymatgen/electronic_structure/bandstructure.py
  pymatgen/electronic_structure/cohp.py
  pymatgen/electronic_structure/plotter.py
  pymatgen/entries/entry_tools.py
  pymatgen/ext/cod.py
  pymatgen/ext/matproj.py
  pymatgen/ext/matproj_legacy.py
  pymatgen/io/lammps/inputs.py
  pymatgen/io/lammps/utils.py
  pymatgen/io/vasp/help.py
  pymatgen/io/vasp/outputs.py
  pymatgen/io/vasp/sets.py
  pymatgen/phonon/plotter.py
  pymatgen/symmetry/analyzer.py
  pymatgen/symmetry/kpath.py
  pymatgen/transformations/advanced_transformations.py
  pymatgen/transformations/standard_transformations.py
  pymatgen/util/coord.py
  pymatgen/util/coord_cython.pyx
  pymatgen/util/plotting.py
  tests/electronic_structure/test_cohp.py
  tests/entries/test_entry_tools.py
  tests/io/vasp/test_sets.py
Labels: qa, housekeeping, dx

#3736 Avoid using `exec` in code
  pymatgen/io/lammps/data.py
  pymatgen/io/lammps/inputs.py
  pymatgen/io/lammps/outputs.py
Labels: qa, security

#3734 Fix `ChemicalPotentialDiagram` 2D plot not respecting `formal_chempots` setting
  pymatgen/analysis/chempot_diagram.py
  tests/analysis/test_chempot_diagram.py
Labels: fix, data viz

#3691 Clean up `core.surface` comments and docstrings
  pymatgen/core/sites.py
  pymatgen/core/structure.py
  pymatgen/core/surface.py
  tests/apps/borg/test_queen.py
  tests/core/test_surface.py
  tests/files/.pytest-split-durations
Labels: fix, core, surfaces

#3745 Fix `io.cp2k.input.DataFile`
  pymatgen/electronic_structure/plotter.py
  pymatgen/io/cp2k/inputs.py
  tests/io/cp2k/test_inputs.py
  tests/io/test_openff.py
Labels: tests, fix, cp2k

#3749 Breaking: all plot methods return `plt.Axes`
  pymatgen/analysis/chempot_diagram.py
  pymatgen/analysis/diffraction/core.py
  pymatgen/analysis/diffraction/neutron.py
  pymatgen/analysis/diffraction/xrd.py
  pymatgen/analysis/ewald.py
  pymatgen/analysis/local_env.py
  pymatgen/analysis/structure_analyzer.py
  pymatgen/analysis/surface_analysis.py
  pymatgen/analysis/wulff.py
  pymatgen/core/composition.py
  pymatgen/core/interface.py
  pymatgen/core/lattice.py
  pymatgen/core/operations.py
  pymatgen/core/structure.py
  pymatgen/core/units.py
  pymatgen/electronic_structure/boltztrap.py
  pymatgen/electronic_structure/boltztrap2.py
  pymatgen/electronic_structure/core.py
  pymatgen/electronic_structure/plotter.py
  pymatgen/entries/compatibility.py
  pymatgen/io/cif.py
  pymatgen/io/common.py
  pymatgen/io/cp2k/sets.py
  pymatgen/io/lobster/outputs.py
  pymatgen/io/nwchem.py
  pymatgen/io/qchem/inputs.py
  pymatgen/io/res.py
  pymatgen/io/vasp/sets.py
  pymatgen/optimization/neighbors.pyx
  pymatgen/phonon/dos.py
  pymatgen/symmetry/groups.py
  pymatgen/transformations/site_transformations.py
  pymatgen/transformations/standard_transformations.py
  pymatgen/util/plotting.py
  tests/analysis/test_wulff.py
  tests/util/test_plotting.py
Labels: qa, data viz, docs, breaking

#3752 Fix `typing_extension` `ImportError` in downstream packages
  .pre-commit-config.yaml
  pymatgen/analysis/elasticity/stress.py
  pymatgen/core/__init__.py
  pymatgen/ext/optimade.py
  pymatgen/io/abinit/netcdf.py
  tests/io/test_packmol.py
  tests/transformations/test_standard_transformations.py
Labels: fix, types

#3754 Update some of the OPTIMADE aliases
  pymatgen/ext/optimade.py
Labels: fix, ext

#3755 Remove duplicate ruff rule in `pyproject.toml`
  pymatgen/analysis/chemenv/connectivity/connected_components.py
  pymatgen/electronic_structure/cohp.py
  pymatgen/io/aims/sets/bs.py
  pymatgen/io/vasp/outputs.py
  pymatgen/io/vasp/sets.py
  pymatgen/phonon/plotter.py
  pymatgen/util/provenance.py
  pymatgen/vis/structure_vtk.py
  pyproject.toml
  tests/io/vasp/test_outputs.py
  tests/phonon/test_init.py
Labels: linting, housekeeping

#3757 `pyright` fixes for `ext/io/phonon/symmetry/transformations/util/vis/dev_scripts` and improve `io.lobster`
  dev_scripts/chemenv/equivalent_indices.py
  dev_scripts/chemenv/strategies/multi_weights_strategy_parameters.py
  dev_scripts/chemenv/view_environment.py
  dev_scripts/update_pt_data.py
  pymatgen/analysis/ewald.py
  pymatgen/analysis/local_env.py
  pymatgen/command_line/enumlib_caller.py
  pymatgen/command_line/vampire_caller.py
  pymatgen/core/ion.py
  pymatgen/core/periodic_table.py
  pymatgen/electronic_structure/boltztrap.py
  pymatgen/ext/matproj_legacy.py
  pymatgen/ext/optimade.py
  pymatgen/io/abinit/abiobjects.py
  pymatgen/io/abinit/inputs.py
  pymatgen/io/abinit/pseudos.py
  pymatgen/io/ase.py
  pymatgen/io/babel.py
  pymatgen/io/cif.py
  pymatgen/io/cp2k/outputs.py
  pymatgen/io/cp2k/sets.py
  pymatgen/io/exciting/inputs.py
  pymatgen/io/feff/inputs.py
  pymatgen/io/fiesta.py
  pymatgen/io/gaussian.py
  pymatgen/io/icet.py
  pymatgen/io/lammps/data.py
  pymatgen/io/lobster/inputs.py
  pymatgen/io/lobster/lobsterenv.py
  pymatgen/io/lobster/outputs.py
  pymatgen/io/nwchem.py
  pymatgen/io/packmol.py
  pymatgen/io/pwscf.py
  pymatgen/io/qchem/outputs.py
  pymatgen/io/vasp/inputs.py
  pymatgen/io/vasp/outputs.py
  pymatgen/io/vasp/sets.py
  pymatgen/io/xr.py
  pymatgen/io/xtb/outputs.py
  pymatgen/io/zeopp.py
  pymatgen/phonon/bandstructure.py
  pymatgen/phonon/gruneisen.py
  pymatgen/phonon/thermal_displacements.py
  pymatgen/symmetry/analyzer.py
  pymatgen/symmetry/bandstructure.py
  pymatgen/symmetry/groups.py
  pymatgen/symmetry/kpath.py
  pymatgen/symmetry/maggroups.py
  pymatgen/transformations/advanced_transformations.py
  pymatgen/util/coord.py
  pymatgen/util/coord_cython.pyx
  pymatgen/util/provenance.py
  pymatgen/util/string.py
  pymatgen/vis/structure_chemview.py
  pymatgen/vis/structure_vtk.py
  pyproject.toml
  tests/files/cohp/lobsterin.1
  tests/files/cohp/lobsterin.3
  tests/io/lobster/test_inputs.py
Labels: linting, housekeeping

#3740 Add type annotations for `io.vasp.inputs/optics`
  dev_scripts/update_pt_data.py
  pymatgen/alchemy/filters.py
  pymatgen/alchemy/transmuters.py
  pymatgen/analysis/chemenv/coordination_environments/coordination_geometries.py
  pymatgen/analysis/chemenv/coordination_environments/structure_environments.py
  pymatgen/analysis/ewald.py
  pymatgen/analysis/structure_prediction/substitution_probability.py
  pymatgen/analysis/wulff.py
  pymatgen/apps/battery/plotter.py
  pymatgen/apps/borg/queen.py
  pymatgen/cli/pmg_analyze.py
  pymatgen/command_line/vampire_caller.py
  pymatgen/core/interface.py
  pymatgen/core/structure.py
  pymatgen/ext/cod.py
  pymatgen/ext/matproj_legacy.py
  pymatgen/io/abinit/abitimer.py
  pymatgen/io/abinit/pseudos.py
  pymatgen/io/cp2k/outputs.py
  pymatgen/io/pwscf.py
  pymatgen/io/qchem/inputs.py
  pymatgen/io/vasp/help.py
  pymatgen/io/vasp/inputs.py
  pymatgen/io/vasp/optics.py
  pymatgen/io/vasp/outputs.py
  pymatgen/io/vasp/sets.py
  pymatgen/io/xtb/outputs.py
  pymatgen/transformations/advanced_transformations.py
  pymatgen/transformations/standard_transformations.py
  pymatgen/vis/plotters.py
  pymatgen/vis/structure_vtk.py
  tasks.py
  tests/apps/battery/test_plotter.py
  tests/ext/test_cod.py
  tests/ext/test_matproj.py
  tests/ext/test_optimade.py
Labels: types

#3779 Add fix for SFAC writer
  pymatgen/io/res.py
  tests/io/test_res.py
Labels: io, fix

#3771 Fix LobsterSet
  pymatgen/io/vasp/sets.py
  tests/io/vasp/test_sets.py
Labels: fix, vasp

#3777 `pyright` fixes
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  dev_scripts/update_pt_data.py
  pymatgen/analysis/adsorption.py
  pymatgen/analysis/bond_dissociation.py
  pymatgen/analysis/bond_valence.py
  pymatgen/analysis/chemenv/coordination_environments/chemenv_strategies.py
  pymatgen/analysis/chemenv/coordination_environments/coordination_geometries.py
  pymatgen/analysis/chemenv/coordination_environments/coordination_geometry_finder.py
  pymatgen/analysis/chemenv/coordination_environments/structure_environments.py
  pymatgen/analysis/chemenv/utils/chemenv_config.py
  pymatgen/analysis/chemenv/utils/scripts_utils.py
  pymatgen/analysis/chempot_diagram.py
  pymatgen/analysis/diffraction/tem.py
  pymatgen/analysis/elasticity/elastic.py
  pymatgen/analysis/functional_groups.py
  pymatgen/analysis/graphs.py
  pymatgen/analysis/local_env.py
  pymatgen/analysis/magnetism/heisenberg.py
  pymatgen/analysis/molecule_matcher.py
  pymatgen/analysis/phase_diagram.py
  pymatgen/analysis/piezo_sensitivity.py
  pymatgen/analysis/quasiharmonic.py
  pymatgen/analysis/structure_analyzer.py
  pymatgen/analysis/structure_matcher.py
  pymatgen/analysis/surface_analysis.py
  pymatgen/analysis/topological/spillage.py
  pymatgen/analysis/transition_state.py
  pymatgen/analysis/wulff.py
  pymatgen/analysis/xas/spectrum.py
  pymatgen/command_line/bader_caller.py
  pymatgen/command_line/chargemol_caller.py
  pymatgen/command_line/critic2_caller.py
  pymatgen/command_line/vampire_caller.py
  pymatgen/core/interface.py
  pymatgen/core/structure.py
  pymatgen/core/surface.py
  pymatgen/core/tensors.py
  pymatgen/core/trajectory.py
  pymatgen/electronic_structure/boltztrap.py
  pymatgen/electronic_structure/boltztrap2.py
  pymatgen/electronic_structure/cohp.py
  pymatgen/electronic_structure/plotter.py
  pymatgen/ext/cod.py
  pymatgen/ext/matproj_legacy.py
  pymatgen/io/vasp/help.py
  tasks.py
  tests/ext/test_cod.py
  tests/ext/test_matproj.py
  tests/ext/test_optimade.py
Labels: linting, types

#3783 Update `vasprun.converged_ionic` logic when `EDIFFG=0`, REDO of PR #3765
  pymatgen/io/vasp/outputs.py
  tests/files/io/vasp/outputs/vasprun.ediffg_set_to_0.xml.gz
  tests/io/vasp/test_outputs.py
  tests/io/vasp/test_sets.py
Labels: io, fix, vasp, ecosystem

#3784 Fix for incorrect file path in `tests/io/test_zeopp.py`
  pymatgen/core/structure.py
  pymatgen/util/due.py
  tests/analysis/test_graphs.py
  tests/io/test_zeopp.py
Labels: tests, io, fix

#3767 Fix for writing non-unique site labels in `CifWriter`
  pymatgen/core/structure.py
  pymatgen/io/cif.py
  tests/core/test_structure.py
  tests/io/test_cif.py
Labels: io, fix, cif

#3758 Convert `kpts` in `Kpoints` to `Sequence[tuple]` and set it as `property`
  pymatgen/core/interface.py
  pymatgen/core/lattice.py
  pymatgen/core/trajectory.py
  pymatgen/io/aims/outputs.py
  pymatgen/io/aims/parsers.py
  pymatgen/io/cif.py
  pymatgen/io/cp2k/inputs.py
  pymatgen/io/lobster/inputs.py
  pymatgen/io/lobster/outputs.py
  pymatgen/io/res.py
  pymatgen/io/vasp/inputs.py
  pymatgen/io/vasp/outputs.py
  pymatgen/io/vasp/sets.py
  pymatgen/util/typing.py
  tests/io/vasp/test_inputs.py
  tests/io/vasp/test_sets.py
Labels: io, vasp, types, api
